apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresDbSecret.secretName }}
  labels:
    {{- include "equitativa.labels" . | nindent 4 }}
type: Opaque

data:
  postgres_password: {{ .Values.postgresDbSecret.dbPassword }}
