apiVersion: v1
kind: Service
metadata:
  name: {{ include "equitativa.fullname" . }}
  labels:
    {{- include "equitativa.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort:  {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "equitativa.selectorLabels" . | nindent 4 }}

